ignore:
  field_paths:
    - CreateFunctionInput.SecurityGroupIDs
    - CreateFunctionInput.SubnetIDs
    - UpdateFunctionInput.SecurityGroupIDs
    - UpdateFunctionInput.SubnetIDs
  resource_names:
    - Alias
    - EventSourceMapping
