ignore:
  field_paths:
    - CreateFunctionInput.VPCConfig.SecurityGroupIDs
    - CreateFunctionInput.VPCConfig.SubnetIDs
    - UpdateFunctionInput.VPCConfig.SecurityGroupIDs
    - UpdateFunctionInput.VPCConfig.SubnetIDs
  resource_names:
    - Alias
    - EventSourceMapping
