apiVersion: lambda.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: test-function
spec:
  forProvider:
    code:
      s3Bucket: "my-s3-bucket"
      s3Key: "prefix/path_to_key.zip"
    environment:
      variables:
        envKey: envValue
    functionName: "test-function"
    handler: "index.handler"
    roleRef:
      name: somerole
    runtime: nodejs12.x
    region: us-east-1
    vpcConfig:
      securityGroupIDRefs:
        - name: sample-sg
      subnetIDRefs:
        - name: sample-subnet1
    tags:
      myKey: myValue
  providerConfigRef:
    name: example
